package com.browserstack;

import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import  org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

public class TechnicalAssignmentAutomate {
    // Generated by Selenium IDE

        private WebDriver driver;
        private Map<String, Object> vars;
        JavascriptExecutor js;
        @BeforeClass
        public void setUp() {
            driver = new ChromeDriver();
            js = (JavascriptExecutor) driver;
            vars = new HashMap<String, Object>();
        }
        @AfterClass
        public void tearDown() {
            driver.quit();
        }
        @Test
        public void testCase4() throws InterruptedException {
            driver.get("https://bstackdemo.com/signin");
            driver.manage().window().setSize(new Dimension(1470, 920));
            driver.findElement(By.xpath("//div[@id=\'username\']/div/div/div")).click();
            driver.findElement(By.id("react-select-2-option-0-0")).click();
            driver.findElement(By.xpath("//div[@id=\'password\']/div/div/div")).click();
            driver.findElement(By.id("react-select-3-option-0-0")).click();
            driver.findElement(By.id("login-btn")).click();
            Thread.sleep(4000);
            driver.findElement(By.xpath("//div[2]/div[4]")).click();
            driver.findElement(By.cssSelector(".buy-btn")).click();
            Thread.sleep(4000);
            driver.findElement(By.id("firstNameInput")).click();
            driver.findElement(By.id("firstNameInput")).sendKeys("Muskan");
            driver.findElement(By.id("lastNameInput")).click();
            driver.findElement(By.id("lastNameInput")).sendKeys("Bahrani");
            driver.findElement(By.id("addressLine1Input")).click();
            driver.findElement(By.id("addressLine1Input")).sendKeys("101-b");
            driver.findElement(By.id("provinceInput")).click();
            driver.findElement(By.id("provinceInput")).sendKeys("mh");
            driver.findElement(By.id("postCodeInput")).click();
            driver.findElement(By.id("postCodeInput")).sendKeys("401");
            driver.findElement(By.id("checkout-shipping-continue")).click();
            driver.findElement(By.cssSelector("*[data-test=\"shipping-address-heading\"]")).click();
            {
                List<WebElement> elements = driver.findElements(By.cssSelector("*[data-test=\"shipping-address-heading\"]"));
                assert(elements.size() > 0);
            }
        }
    }
